### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by mapfap** [kamontat/lab9#5]
UI class of UnitConverter should not create UnitConverter (controller) object. It should use dependency injection in the constructor.

Example
```java
// main method
UnitConverter unitConverter = new UnitConverter();
ConverterUI ui = new ConverterUI(unitConverter);

// ConverterUI's constructor
public ConverterUI(UnitConverter unitConverter) {
```

This allows a program design to follow the [Dependency Inversion Principle](https://en.wikipedia.org/wiki/Dependency_inversion_principle), which decoupling software modules.

**Comment by kamontat** [comment]
พี่อธิบายเป็น ภาษาไทยได้ไหมอะครับ ??  ว่ามันต่างกันยังไงอะครับ 
ผมอ่านไม่ค่อยเข้าใจเลยอะครับ

**Comment by mapfap** [comment]
คือตอนนี้เรามี โค้ด 2 ส่วนหลักๆ คือ
1. UI ที่จัดการเรื่องการแสดงผล/รับค่า (MainConvertWindow)
2. Logic ที่คอยคำนวณค่า/แปลงหน่วย  (UnitConverter)
" ขอเรียกแต่ละส่วนว่า module "
- ทีนี้ในหลักการของ OOP, มันมีตัวนึงชื่อว่า Dependency Inversion Principle (DIP)
  ซึ่งมันต้องการที่จะ decoupling module "ทำให้โมดูล ไม่ขึ้นต่อกัน"
- แล้วก่อนหน้านี้ ถ้าเราให้ MainConvertWindow สร้าง UnitConverter. มันทำให้**เกิดdependency** คือ MainConvertWindow มัน depend on(ขึ้นต่อ) UnitConverter
- _มันไม่ใช้หน้าที่ของ UI ที่จะมาคอยกังวล(depend on)ว่าจะใช้ logic แบบไหน_
- หนึ่งในวิธีที่จะทำให้เราลุล่วง DIP, ก็คือ Dependency Injection ซึ่งก็มีหลายวิธีย่อย ๆ อีก. แต่ว่าแบบที่น่าจะเข้าใจง่าย ก็คือ Constructor Injection ซึ่งก็คือ
```java
// ใน main
UnitConverter unitConverter = new UnitConverter(); // สร้าง UnitConverter
ConverterUI ui = new ConverterUI(unitConverter); // INJECT unitConverter ผ่าน constructor
```
>>**แทนที่จะให้ UI คอยกังวลว่าจะใช้ logic แบบไหนดี -> ปล่อยให้เป็นหน้าที่ของ main เอา logic ยัดใส่มาให้ ผ่าน constructor**

...งงกว่าเดิมหรือเปล่าครับ? 55
